default_install_hook_types: [pre-commit, prepare-commit-msg]
ci:
  autofix_commit_msg: "chore: Auto update by pre-commit hooks [skip changelog]"
  autofix_prs: true
repos:
  - repo: https://github.com/shssoichiro/oxipng
    rev: v9.1.2
    hooks:
      - id: oxipng
        args: ["-q", "-o", "2", "-s", "--ng"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        # Limit prettier to run only on docs, .github workflows and README/package files
        files: ^(docs/|\.github/|README\.md|package.json|\.github/workflows/).*\.(ya?ml|json|md)$
        types_or:
          - yaml
          - json
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
      - id: markdownlint-cli2
        files: ^docs/.*|^README\.md$
        types:
          - markdown
        args: ["--fix", "--config", "docs/.markdownlint.yaml", "#**/node_modules"]